#!/bin/sh

echo "clean root"
rm -rf root
mkdir root

echo "copy static content"
cp -r static/* root/
cp -r deps/deserted-fonts/build/*.ttf root/assets/fonts

echo "generate feeds"
cp feed/feed.twtxt root
twtxt-tmpl feed/feed.twtxt feed/atom.tmpl root/feed.atom
twtxt-tmpl feed/feed.twtxt feed/html.tmpl root/feed.html

echo "generate pages"
for page in pages/*.runo; do
  echo " $page"
  runo page.tmpl "$page" > "root/$(basename "$page" .runo).html"
done

echo pages/theming/theming.runo
runo page.tmpl pages/theming/theming.runo > "root/theming.html"
for img in pages/theming/*.png; do
  echo "$img"
  cp "$img" "root/theming_$(basename "$img")"
done

# keep old links alive :p
mkdir root/articles
cp root/adler32.html root/articles/adler32.html