name: Deploy www

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]
    paths:
      - 'www/**'
      - 'twtxt-tmpl/**'
      - 'runo/**'
      - 'deserted-fonts/**'
      - '.github/workflows/gh-pages.yml'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  JANET_TREE: ${{github.workspace}}/jpm_tree

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3.5.0
      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Install janet
        run: |
          git clone https://github.com/janet-lang/janet.git
          cd janet
          make -j $(nproc)
          make test
          sudo make install

      - name: Install jpm
        run: |
          git clone --depth=1 https://github.com/janet-lang/jpm.git
          cd jpm
          sudo janet bootstrap.janet

      - name: Generate pages
        run: |
          . ./env
          cd www
          make

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "www/root"

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
